name: Snapshot Artifacts

on:
  workflow_dispatch:

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.5

      - run: bun install

      - run: bunx tsci snapshot --update --force-update

      - uses: actions/upload-artifact@v4
        with:
          name: snapshots
          path: |
            __snapshots__/
            lib/Microcontroller_RP2350/__snapshots__/
